---
name: WWW-Pastebin-PastebinCa-Retrieve
version: 0.001
author:
  - 'Zoffix Znet <zoffix@cpan.org>'
abstract: a module to retrieve pastes from http://pastebin.ca/ website
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  HTML::Entities: 1.35
  HTML::TokeParser::Simple: 3.15
  WWW::Pastebin::Base::Retrieve: 0.001
build_requires:
  Test::More: 0
provides:
  WWW::Pastebin::PastebinCa::Retrieve:
    file: lib/WWW/Pastebin/PastebinCa/Retrieve.pm
    version: 0.001
generated_by: Module::Build version 0.2808
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
